### PR TITLE
Update the documentation structure

### PR DESCRIPTION
**Pull request by Thomsch**
This pull request update the structure of the documentation in preparation of the changes in the getting started guide.

The objective is to make the documentation more intuitive, especially for newcomers.

### CODE REVIEW

**Comment by bouthilx** [comment]
Looks good! Can you please remind me what's the plan for the sections? Like where getting started should go, and overview.

**Comment by Thomsch** [comment]
Getting Started will go in **Welcome** and Overview will go in **User Guide**.
Getting Started will give a brief tour of Oríon and point to the examples.
Overview is the landing page for the User Guide, and contain high level information about the application.

**Comment by bouthilx** [comment]
Perfect! Re-opening to trigger travis (again...)

**Comment by bouthilx** [comment]
I relaunched the failed test. This annoying random failure will be fixed by #373

**Pull request merged**
