### PR TITLE
Add Python 3.10

### PR DESCRIPTION
**Pull request by Delaunay**
Add Python 3.10

### CODE REVIEW

**Comment by lebrice** [comment]
Fixes #846

**Comment by bouthilx** [comment]
Conda issue is already reported here: https://github.com/conda/conda/issues/11442.

**Comment by bouthilx** [comment]
We must make sure to update DEHB dependency and point back to main repo when 3.7 is dropped.

**Review by bouthilx — APPROVED** [review]
Thanks!

**Pull request merged**
