### PR TITLE
Handle broken trials with python API

### PR DESCRIPTION
**Pull request by bouthilx**
Why:

If the process exits, the trial status stays to `reserved` and will
eventually be set to `interrupted`.

How:

Register a function to release the remaining trials with pacemakers. If
the process exits normally (no signup signals or sigterm), the function
will be called and all reserved trials will be set to broken.

### CODE REVIEW

**Comment by bouthilx** [comment]
[Handle broken trials with python API](https://trello.com/c/A1kRqDur/335-handle-broken-trials-with-python-api)

**Comment by bouthilx** [comment]
Codecov test is totally broken, coverage is not decreased by the PR.

**Comment by Delaunay** [comment]
Actually if we are going to have an explicit `experiment.close()` I would be in favor of implementing it as a context as well with `__enter__` and `__exit__` so users do not have to think about it

**Comment by bouthilx** [comment]
I agree that having support for close through a context manager would be great, but since the call to `close()` is not mandatory (not doing so just clutters atexit but it doesn't cause any issue), I think forcing the use of the context manager would be too much hassle for the user for what it's worth. Maybe we can make a trello card to add support for both explicit `close()` and contextmanager, like builtin `open()`.

**Pull request merged**
