### PR TITLE
Remove Orion space

### PR DESCRIPTION
**Pull request by Delaunay**
_Hi there! Thank you for contributing. Feel free to use this pull request template; It helps us reviewing your work at its true value._

_Please remove the instructions in italics before posting the pull request :)._

# Description
_Describe what is the purpose of this pull request and why it should be integrated to the repository. 
When your changes modify the current behavior, explain why your solution is better._

_If it solves a GitHub issue, be sure to [link it](https://help.github.com/en/github/writing-on-github/autolinked-references-and-urls#issues-and-pull-requests)._

# Changes
_Give an overview of the suggested solution._

# Checklist
_This is simply a reminder of what we are going to look for before merging your code._

_Add an `x` in the boxes that apply._
_If you're unsure about any of them, don't hesitate to ask. We're here to help!_ 
_You can also fill these out after creating the PR if it's a work in progress (be sure to publish the PR as a draft then)_

## Tests
- [ ] I added corresponding tests for bug fixes and new features. If possible, the tests fail without the changes
- [ ] All new and existing tests are passing (`$ tox -e py38`; replace `38` by your Python version if necessary)

## Documentation
- [ ] I have updated the relevant documentation related to my changes

## Quality
- [ ] I have read the [CONTRIBUTING](https://github.com/Epistimio/orion/blob/develop/CONTRIBUTING.md) doc
- [ ] My commits messages follow [this format](https://chris.beams.io/posts/git-commit/)
- [ ] My code follows the style guidelines (`$ tox -e lint`)

# Further comments
_Please include any additional information or comment that you feel will be helpful to the review of this pull request._

### CODE REVIEW

**Comment by lebrice** [comment]
Wait, is there going to be some backward-compatibility guarantees here? What is the space going to be replaced with?

**Comment by Delaunay** [comment]
sample space, it will be backward compatible

**Review by lebrice — CHANGES_REQUESTED** [review]
I don't know if this PR is meant to be ready for review or not, but I'd expect big changes like this to be backward-compatible. (I've been using `orion.algo.space.Space` a lot)

**Comment by lebrice** [comment]
@Delaunay Could you keep the modules alive here, and replace their content with the equivalent imports from sample_space? What do you think @bouthilx?

Also, I'd suggest that we leave the tests modules related to spaces, as a test for the replacements mentioned above. If we don't want to duplicate tests, then I'd suggest we import the tests from sample-space into our test modules, so they get run alongside those of Orion.

**Comment by Delaunay** [comment]
The tests are very precise in what they are checking, they still exist in sample space, running them twice is not going to help coverage in anyway.

The appropriate modules will be added back when required

**Comment by lebrice** [comment]
> The tests are very precise in what they are checking, they still exist in sample space, running them twice is not going to help coverage in anyway.

I don't doubt that Sample-space must have good tests, that's not what I'm worried about. I'm worried about `orion.algo.robo`, `orion.algo.hebo`, my own warm-starting-related code, and all the other plugins that have references to the `Space` class from orion, or any space-related utility functions.  Those can't be ripped out from Orion without providing a backward-compatible inferface. The tests should stay, or replaced with an import, in order to guarantee this seamless transition. This isn't running tests twice. Let me know if there's something I'm missing here.

> The appropriate modules will be added back when required

The space module is 100% required, right now. For the transformation functions it's not 100% clear to me which ones could safely be removed.

**Comment by bouthilx** [comment]
I think keeping the tests during deprecation phase is a fairly simple way to ensure backward compatibility. Obviously we would not want to maintain these tests later on, and they should be removed when we remove the classes in orion.algo.space and others. For now I would suggest replacing the classes with `def ClassName(*args, **kwargs)` that logs a deprecation warning and returns the corresponding object imported from sample space.

**Pull request closed without merging**
