### PR TITLE
Add config option `frontends_uri` to specify allowed frontend addresses for Orion Web API

### PR DESCRIPTION
**Pull request by notoraptor**
# Description
Hi @bouthilx ! This is a pull request to wrap all changes related to CORS handling for Orion Web API. I will close other related pull requests so that we can focus only on this one.

This PR adds option `frontends_uri` to list allowed frontend addresses and add `falcon-cors` dependencies for PYPI (using original package) and conda (using conda package I built from PYPI package and uploaded on my anaconda repo)

# Changes

- Re-add changes reverted from https://github.com/Epistimio/orion/pull/792
- Add changes from https://github.com/bouthilx/orion/pull/4
  - Changes should fix https://github.com/Epistimio/orion/issues/793
  - Changes should resolve issue from https://github.com/Epistimio/orion/pull/780
- Add changes from https://github.com/Epistimio/orion/pull/782
  - Changes should fix https://github.com/Epistimio/orion/issues/779

# Checklist

## Tests
- [x] I added corresponding tests for bug fixes and new features. If possible, the tests fail without the changes
- [x] All new and existing tests are passing (`$ tox -e py38`; replace `38` by your Python version if necessary)

## Documentation
- [x] I have updated the relevant documentation related to my changes

## Quality
- [ ] I have read the [CONTRIBUTING](https://github.com/Epistimio/orion/blob/develop/CONTRIBUTING.md) doc
- [ ] My commits messages follow [this format](https://chris.beams.io/posts/git-commit/)
- [ ] My code follows the style guidelines (`$ tox -e lint`)

# Further comments
_Please include any additional information or comment that you feel will be helpful to the review of this pull request._

### CODE REVIEW

**Comment by bouthilx** [comment]
Thanks! Ideally the conda packaging of falcon-cors should be integrated in our packaging pipeline to make sure we update it properly over time. However we should not expect to much changes in falcon-cors since last updates were 2 years ago. That leads me to another question; Is it a good idea to depend on this package, which does not seam maintained anymore, to address security concerns? I'm not sure...

**Comment by notoraptor** [comment]
@bouthilx Indeed, it's an old package.

Maybe I could just copy the code (with citation) directly into orion, as it's a matter of 2 classes (CORS + CORSMiddleware), so that we won't need any dependency anymore?

**Comment by bouthilx** [comment]
For reference, after discussion with @notoraptor we decided to fork falcon-cors into @mila-iqia to maintain it ourselves. The code itself is not expected to evolve a lot since it is mostly just related to the CORS standard, but the tests may needs adjustments based on changes in falcon.testing.TestCase. We will also publish falcon-cors in the mila-iqia forge.

**Comment by notoraptor** [comment]
@bouthilx PR updated, and conda package `falcon-cors` copied into `mila-iqia` channel: https://anaconda.org/mila-iqia/falcon-cors

However, it seems I don't have rights on github `mila-iqia` organization to fork `falcon-cors` repo into.

**Comment by notoraptor** [comment]
`falcon-cors` is forked into `mila-iqia` @bouthilx ! https://github.com/mila-iqia/falcon-cors

**Review by bouthilx — APPROVED** [review]
All good for this PR then, thanks!

**Pull request merged**
