### PR TITLE
Drop support for python 3.6

### PR DESCRIPTION
**Pull request by lebrice**
Title.

This is going to enable us to use nice type hints everywhere thanks to https://peps.python.org/pep-0563/

### CODE REVIEW

**Comment by bouthilx** [comment]
I suggest we bump all tests to py3.9 by default. They are currently at py3.7.

**Comment by lebrice** [comment]
I'd rather do that in another PR, in the interest of time. Is that ok with you @bouthilx ?

**Comment by lebrice** [comment]
Created another pr for that: #855

**Review by bouthilx — APPROVED** [review]
All good, thanks!

**Pull request merged**
