### PR TITLE
Citing section

### PR DESCRIPTION
**Pull request by DatCorno**

### CODE REVIEW

**Comment by bouthilx** [comment]
There should only be one commit. :) Do we want people to cite the github repo, or a published paper?

**Comment by DatCorno** [comment]
The 162 commits are from develop aha. Also, I think the citation should be for the repo à la nevergrad.

**Comment by bouthilx** [comment]
They should not appear if they are from develop and you try to merge to develop. Try refreshing your develop branch and rebasing this branch again.

I'm not sure citations to github will count like citations in h-indexes.

**Comment by DatCorno** [comment]
I actually just edited it on Github and use their automatic process to commit it, it must have bugged out. Also, notice it merges on master, that's why all the develop commit are showing ;)

**Comment by DatCorno** [comment]
I used the edit thing on Github, but I'll just make a local change.

**Comment by bouthilx** [comment]
Oh, you clicked edit from the master branch I guess?

**Comment by DatCorno** [comment]
I did.

**Comment by bouthilx** [comment]
As discussed offline, we'll wait to have a published paper to add citations in the documentation.

**Pull request closed without merging**
