### PR TITLE
Enhance table

### PR DESCRIPTION
**Pull request by notoraptor**
# Description

Hi @bouthilx , this is a PR with some enhancements for trials table

# Changes

- Use light gray for empty column headers
- Allow to display all columns (useful if many columns are hidden) using a checkbox added in multiselect
- Add drag-and-drop to change columns order
- Display trial info in a dialog when clicking on trial row

# Checklist

## Tests
- [ ] I added corresponding tests for bug fixes and new features. If possible, the tests fail without the changes
- [ ] All new and existing tests are passing (`$ tox -e py38`; replace `38` by your Python version if necessary)

## Documentation
- [ ] I have updated the relevant documentation related to my changes

## Quality
- [ ] I have read the [CONTRIBUTING](https://github.com/Epistimio/orion/blob/develop/CONTRIBUTING.md) doc
- [ ] My commits messages follow [this format](https://chris.beams.io/posts/git-commit/)
- [ ] My code follows the style guidelines (`$ tox -e lint`)

### CODE REVIEW

**Comment by notoraptor** [comment]
TODO: Use instead a checkbox to "select all"

Put checkbox at top of columns in multiselect component

If all columns are selected, this checkbox should be selected

If any column is deselected, this checkbox should be deselected

**Comment by notoraptor** [comment]
Finally added drag-and-drop to change column order!

**Comment by notoraptor** [comment]
@bouthilx Updated!

* Display trial info in a dialog when clicking on trial row

**Comment by notoraptor** [comment]
PS: We may need a demo to correctly review all changes ^^ !

**Review by bouthilx — APPROVED** [review]

**Pull request merged**
