### PR TITLE
 Add Linearize transform and linear requirement

### PR DESCRIPTION
**Pull request by bouthilx**
Why:

Some algorithms works better if the space is linearized. If the algo is
sampling from another internal prior for instance, the algorithm would
need to lookup on the space to see if the dimension has a logarithmic
distribution in order to adapt the internal prior.

How:

Turn all dimensions to `real`, and those with logarithmic distribution
are then further linearized by taking the log.

Note:

Also modifies `unpack_point` and `pack_point` to make them idempotent.

### CODE REVIEW

**Comment by bouthilx** [comment]
@tsirif Would have some time to take a look at this?

**Comment by bouthilx** [comment]
Little update. It seems the bayesian optimizer built on top of scikit-optimizer is not sampling from log-uniform but rather uniform. So it turns out this linearization would be very helpful to improve the bayesian optimizer as well.

**Comment by bouthilx** [comment]
[Add Linearisation](https://trello.com/c/Qh7JkloX/75-add-linearisation)

**Comment by Thomsch** [comment]
Forcing Travis to migrate to .com

**Pull request closed without merging**
