### PR TITLE
Make sure subprocess/process/thread/dask can create a runner instance

### PR DESCRIPTION
**Pull request by Delaunay**
_Hi there! Thank you for contributing. Feel free to use this pull request template; It helps us reviewing your work at its true value._

_Please remove the instructions in italics before posting the pull request :)._

# Description
_Describe what is the purpose of this pull request and why it should be integrated to the repository. 
When your changes modify the current behavior, explain why your solution is better._

_If it solves a GitHub issue, be sure to [link it](https://help.github.com/en/github/writing-on-github/autolinked-references-and-urls#issues-and-pull-requests)._

# Changes
_Give an overview of the suggested solution._

# Checklist
_This is simply a reminder of what we are going to look for before merging your code._

_Add an `x` in the boxes that apply._
_If you're unsure about any of them, don't hesitate to ask. We're here to help!_ 
_You can also fill these out after creating the PR if it's a work in progress (be sure to publish the PR as a draft then)_

## Tests
- [ ] I added corresponding tests for bug fixes and new features. If possible, the tests fail without the changes
- [ ] All new and existing tests are passing (`$ tox -e py38`; replace `38` by your Python version if necessary)

## Documentation
- [ ] I have updated the relevant documentation related to my changes

## Quality
- [ ] I have read the [CONTRIBUTING](https://github.com/Epistimio/orion/blob/develop/CONTRIBUTING.md) doc
- [ ] My commits messages follow [this format](https://chris.beams.io/posts/git-commit/)
- [ ] My code follows the style guidelines (`$ tox -e lint`)

# Further comments
_Please include any additional information or comment that you feel will be helpful to the review of this pull request._

### CODE REVIEW

**Comment by Delaunay** [comment]
#807

**Review by bouthilx — APPROVED** [review]
Thanks!

**Comment by jbeirer** [comment]
Hi @Delaunay,

thanks for looking into this. Indeed, I did not have these kind of issues in the previous 0.2.1 version. The most minimal reproducer I can come up with in order to reproduce #807 is running two experiments in parallel:

```python
# Orion includes
from orion.executor.base import executor_factory
from distributed import Client
from orion.client import build_experiment

# Dask includes
import dask
import dask.distributed

# Dummy method
def main():
    return [ {"name": "error", "type": "objective", "value": 1}]

if __name__ == '__main__':

  ########################################################################
  ### Assumes cluster, space, storage and algorithm variables are set ###
  ########################################################################

  # Set number of trials and workers
  nMaxTrials = 1
  nWorkers = 1 

  # Initialize client
  client  = Client(cluster) 
  cluster.scale(nWorkers)

  # Create DASK executor
  executor = executor_factory.create('dask', n_workers = nWorkers, client = client)

  # Encapsulate experiment execution in method to parellelise experiments
  def exec_experiment(executor, nWorkers, experiment):
      experiment.workon(main, n_workers = nWorkers)

  # Build two experiments to run in parallel
  experimentNames = ['experiment1', 'experiment2']
  exp_futures = []
  for experimentName in experimentNames:
      experiment = build_experiment(name = name, max_trials  = nMaxTrials, space = space, storage = storage, algorithms = algorithm, executor = executor)
      future     = client.submit(exec_experiment, executor, nWorkers, experiment)
      exp_futures.append(future)

  # Gather results
  for exp_future in exp_futures:
      client.gather(exp_future)
```

Hope this helps!

Cheers,

Joshua

**Comment by Delaunay** [comment]
@jbeirer I think I identified the root cause, the issue should be resolved now

**Pull request merged**
